server.port=4321
// --- application.properties ---
# Database configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=guru

## PostgreSQL Database Configuration
#spring.datasource.url=jdbc:postgresql://<your-database-host>:5432/<your-database-name>
#spring.datasource.username=<your-username>
#spring.datasource.password=<your-password>
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.platform=postgresql
#
## JPA/Hibernate Config
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update  # Can be 'validate', 'update', 'create', or 'none' based on your needs
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# Hibernate configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Show SQL in logs
spring.jpa.show-sql=true

# H2 Console Enable
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
